<?php
	namespace sednasoft\virmisco\readlayer\valueobject;
	/**
	 * Do not edit. This class was automatically generated by codegen/read-layer/generator.php on
	 * 2016-01-13T22:53:08+01:00
	 */
	class FocalPlaneImageExposureSettings {
		/** @var double|null */
		protected $duration = null;
		/** @var double|null */
		protected $gain = null;

		/**
		 * @param double|null $duration
		 * @param double|null $gain
		 */
		public function __construct ($duration = null, $gain = null) {
			$this->duration = $duration;
			$this->gain = $gain;
		}

		/**
		 * @return double|null
		 */
		public function getDuration () {
			return $this->duration;
		}

		/**
		 * @return double|null
		 */
		public function getGain () {
			return $this->gain;
		}
	}
