<?php
	namespace sednasoft\virmisco\readlayer\valueobject;
	/**
	 * Do not edit. This class was automatically generated by codegen/read-layer/generator.php on
	 * 2016-01-13T22:53:08+01:00
	 */
	class FocalPlaneImagePostProcessingSettings {
		/** @var boolean|null */
		protected $shading = null;
		/** @var boolean|null */
		protected $sharpening = null;

		/**
		 * @param boolean|null $shading
		 * @param boolean|null $sharpening
		 */
		public function __construct ($shading = null, $sharpening = null) {
			$this->shading = $shading;
			$this->sharpening = $sharpening;
		}

		/**
		 * @return boolean|null
		 */
		public function getShading () {
			return $this->shading;
		}

		/**
		 * @return boolean|null
		 */
		public function getSharpening () {
			return $this->sharpening;
		}
	}
