<?php
	namespace sednasoft\virmisco\readlayer\valueobject;
	/**
	 * Do not edit. This class was automatically generated by codegen/read-layer/generator.php on
	 * 2016-01-13T22:53:08+01:00
	 */
	class GatheringAgent {
		/** @var null|string */
		protected $organization = null;
		/** @var null|string */
		protected $person = null;

		/**
		 * @param null|string $person
		 * @param null|string $organization
		 */
		public function __construct ($person = null, $organization = null) {
			$this->person = $person;
			$this->organization = $organization;
		}

		/**
		 * @return null|string
		 */
		public function getOrganization () {
			return $this->organization;
		}

		/**
		 * @return null|string
		 */
		public function getPerson () {
			return $this->person;
		}
	}
