<?php
	namespace sednasoft\virmisco\readlayer\valueobject;
	/**
	 * Do not edit. This class was automatically generated by codegen/read-layer/generator.php on
	 * 2016-01-13T22:53:08+01:00
	 */
	class GatheringLocation {
		/** @var null|string */
		protected $country = null;
		/** @var null|string */
		protected $place = null;
		/** @var null|string */
		protected $province = null;
		/** @var null|string */
		protected $region = null;

		/**
		 * @param null|string $country
		 * @param null|string $province
		 * @param null|string $region
		 * @param null|string $place
		 */
		public function __construct ($country = null, $province = null, $region = null, $place = null) {
			$this->country = $country;
			$this->province = $province;
			$this->region = $region;
			$this->place = $place;
		}

		/**
		 * @return null|string
		 */
		public function getCountry () {
			return $this->country;
		}

		/**
		 * @return null|string
		 */
		public function getPlace () {
			return $this->place;
		}

		/**
		 * @return null|string
		 */
		public function getProvince () {
			return $this->province;
		}

		/**
		 * @return null|string
		 */
		public function getRegion () {
			return $this->region;
		}
	}
