<?php
	namespace sednasoft\virmisco\readlayer\valueobject;
	/**
	 * Do not edit. This class was automatically generated by codegen/read-layer/generator.php on
	 * 2016-01-13T22:53:08+01:00
	 */
	class GatheringSamplingDate {
		/** @var null|string */
		protected $after = null;
		/** @var null|string */
		protected $before = null;

		/**
		 * @param null|string $after
		 * @param null|string $before
		 */
		public function __construct ($after = null, $before = null) {
			$this->after = $after;
			$this->before = $before;
		}

		/**
		 * @return null|string
		 */
		public function getAfter () {
			return $this->after;
		}

		/**
		 * @return null|string
		 */
		public function getBefore () {
			return $this->before;
		}
	}
