<?php
	namespace sednasoft\virmisco\readlayer\valueobject;
	/**
	 * Do not edit. This class was automatically generated by codegen/read-layer/generator.php on
	 * 2016-01-13T22:53:08+01:00
	 */
	class OrganismIdentification {
		/** @var null|string */
		protected $identifier = null;
		/** @var null|string */
		protected $qualifier = null;

		/**
		 * @param null|string $identifier
		 * @param null|string $qualifier
		 */
		public function __construct ($identifier = null, $qualifier = null) {
			$this->identifier = $identifier;
			$this->qualifier = $qualifier;
		}

		/**
		 * @return null|string
		 */
		public function getIdentifier () {
			return $this->identifier;
		}

		/**
		 * @return null|string
		 */
		public function getQualifier () {
			return $this->qualifier;
		}
	}
