<?php
	namespace sednasoft\virmisco\readlayer\valueobject;
	/**
	 * Do not edit. This class was automatically generated by codegen/read-layer/generator.php on
	 * 2016-01-13T22:53:08+01:00
	 */
	class PhotomicrographMicroscopeSettings {
		/** @var double|null */
		protected $aperture_diaphragm_opening = null;
		/** @var null|string */
		protected $contrast_method = null;
		/** @var double|null */
		protected $dic_prism_position = null;
		/** @var double|null */
		protected $field_diaphragm_opening = null;
		/** @var double|null */
		protected $magnification_changer_magnification = null;

		/**
		 * @param null|string $contrastMethod
		 * @param double|null $dicPrismPosition
		 * @param double|null $apertureDiaphragmOpening
		 * @param double|null $fieldDiaphragmOpening
		 * @param double|null $magnificationChangerMagnification
		 */
		public function __construct ($contrastMethod = null, $dicPrismPosition = null, $apertureDiaphragmOpening = null, $fieldDiaphragmOpening = null, $magnificationChangerMagnification = null) {
			$this->contrast_method = $contrastMethod;
			$this->dic_prism_position = $dicPrismPosition;
			$this->aperture_diaphragm_opening = $apertureDiaphragmOpening;
			$this->field_diaphragm_opening = $fieldDiaphragmOpening;
			$this->magnification_changer_magnification = $magnificationChangerMagnification;
		}

		/**
		 * @return double|null
		 */
		public function getApertureDiaphragmOpening () {
			return $this->aperture_diaphragm_opening;
		}

		/**
		 * @return null|string
		 */
		public function getContrastMethod () {
			return $this->contrast_method;
		}

		/**
		 * @return double|null
		 */
		public function getDicPrismPosition () {
			return $this->dic_prism_position;
		}

		/**
		 * @return double|null
		 */
		public function getFieldDiaphragmOpening () {
			return $this->field_diaphragm_opening;
		}

		/**
		 * @return double|null
		 */
		public function getMagnificationChangerMagnification () {
			return $this->magnification_changer_magnification;
		}
	}
