<?php
	namespace sednasoft\virmisco\readlayer\valueobject;
	/**
	 * Do not edit. This class was automatically generated by codegen/read-layer/generator.php on
	 * 2016-01-13T22:53:08+01:00
	 */
	class PhotomicrographCamera {
		/** @var integer|null */
		protected $active_pixels_hor = null;
		/** @var integer|null */
		protected $active_pixels_ver = null;
		/** @var null|string */
		protected $adc_resolution = null;
		/** @var null|string */
		protected $camera_article_or_serial_number = null;
		/** @var null|string */
		protected $camera_maker = null;
		/** @var null|string */
		protected $camera_name = null;
		/** @var null|string */
		protected $capture_format = null;
		/** @var double|null */
		protected $chip_height = null;
		/** @var double|null */
		protected $chip_width = null;
		/** @var null|string */
		protected $color_filter_array = null;
		/** @var double|null */
		protected $dynamic_range = null;
		/** @var null|string */
		protected $optical_format = null;
		/** @var double|null */
		protected $pixel_height = null;
		/** @var double|null */
		protected $pixel_width = null;
		/** @var null|string */
		protected $protective_color_filter = null;
		/** @var null|string */
		protected $readout_noise = null;
		/** @var null|string */
		protected $sensor_article_or_serial_number = null;
		/** @var null|string */
		protected $sensor_maker = null;
		/** @var null|string */
		protected $sensor_name = null;
		/** @var double|null */
		protected $snr_max = null;

		/**
		 * @param null|string $cameraMaker
		 * @param null|string $cameraName
		 * @param null|string $cameraArticleOrSerialNumber
		 * @param null|string $sensorMaker
		 * @param null|string $sensorName
		 * @param null|string $sensorArticleOrSerialNumber
		 * @param null|string $opticalFormat
		 * @param null|string $captureFormat
		 * @param double|null $chipWidth
		 * @param double|null $chipHeight
		 * @param double|null $pixelWidth
		 * @param double|null $pixelHeight
		 * @param integer|null $activePixelsHor
		 * @param integer|null $activePixelsVer
		 * @param null|string $colorFilterArray
		 * @param null|string $protectiveColorFilter
		 * @param null|string $adcResolution
		 * @param double|null $dynamicRange
		 * @param double|null $snrMax
		 * @param null|string $readoutNoise
		 */
		public function __construct ($cameraMaker = null, $cameraName = null, $cameraArticleOrSerialNumber = null, $sensorMaker = null, $sensorName = null, $sensorArticleOrSerialNumber = null, $opticalFormat = null, $captureFormat = null, $chipWidth = null, $chipHeight = null, $pixelWidth = null, $pixelHeight = null, $activePixelsHor = null, $activePixelsVer = null, $colorFilterArray = null, $protectiveColorFilter = null, $adcResolution = null, $dynamicRange = null, $snrMax = null, $readoutNoise = null) {
			$this->camera_maker = $cameraMaker;
			$this->camera_name = $cameraName;
			$this->camera_article_or_serial_number = $cameraArticleOrSerialNumber;
			$this->sensor_maker = $sensorMaker;
			$this->sensor_name = $sensorName;
			$this->sensor_article_or_serial_number = $sensorArticleOrSerialNumber;
			$this->optical_format = $opticalFormat;
			$this->capture_format = $captureFormat;
			$this->chip_width = $chipWidth;
			$this->chip_height = $chipHeight;
			$this->pixel_width = $pixelWidth;
			$this->pixel_height = $pixelHeight;
			$this->active_pixels_hor = $activePixelsHor;
			$this->active_pixels_ver = $activePixelsVer;
			$this->color_filter_array = $colorFilterArray;
			$this->protective_color_filter = $protectiveColorFilter;
			$this->adc_resolution = $adcResolution;
			$this->dynamic_range = $dynamicRange;
			$this->snr_max = $snrMax;
			$this->readout_noise = $readoutNoise;
		}

		/**
		 * @return integer|null
		 */
		public function getActivePixelsHor () {
			return $this->active_pixels_hor;
		}

		/**
		 * @return integer|null
		 */
		public function getActivePixelsVer () {
			return $this->active_pixels_ver;
		}

		/**
		 * @return null|string
		 */
		public function getAdcResolution () {
			return $this->adc_resolution;
		}

		/**
		 * @return null|string
		 */
		public function getCameraArticleOrSerialNumber () {
			return $this->camera_article_or_serial_number;
		}

		/**
		 * @return null|string
		 */
		public function getCameraMaker () {
			return $this->camera_maker;
		}

		/**
		 * @return null|string
		 */
		public function getCameraName () {
			return $this->camera_name;
		}

		/**
		 * @return null|string
		 */
		public function getCaptureFormat () {
			return $this->capture_format;
		}

		/**
		 * @return double|null
		 */
		public function getChipHeight () {
			return $this->chip_height;
		}

		/**
		 * @return double|null
		 */
		public function getChipWidth () {
			return $this->chip_width;
		}

		/**
		 * @return null|string
		 */
		public function getColorFilterArray () {
			return $this->color_filter_array;
		}

		/**
		 * @return double|null
		 */
		public function getDynamicRange () {
			return $this->dynamic_range;
		}

		/**
		 * @return null|string
		 */
		public function getOpticalFormat () {
			return $this->optical_format;
		}

		/**
		 * @return double|null
		 */
		public function getPixelHeight () {
			return $this->pixel_height;
		}

		/**
		 * @return double|null
		 */
		public function getPixelWidth () {
			return $this->pixel_width;
		}

		/**
		 * @return null|string
		 */
		public function getProtectiveColorFilter () {
			return $this->protective_color_filter;
		}

		/**
		 * @return null|string
		 */
		public function getReadoutNoise () {
			return $this->readout_noise;
		}

		/**
		 * @return null|string
		 */
		public function getSensorArticleOrSerialNumber () {
			return $this->sensor_article_or_serial_number;
		}

		/**
		 * @return null|string
		 */
		public function getSensorMaker () {
			return $this->sensor_maker;
		}

		/**
		 * @return null|string
		 */
		public function getSensorName () {
			return $this->sensor_name;
		}

		/**
		 * @return double|null
		 */
		public function getSnrMax () {
			return $this->snr_max;
		}
	}
