<?php
	namespace sednasoft\virmisco\readlayer\valueobject;
	/**
	 * Do not edit. This class was automatically generated by codegen/read-layer/generator.php on
	 * 2016-01-13T22:53:08+01:00
	 */
	class PhotomicrographDetailOf {
		/** @var integer|null */
		protected $hotspot__x = null;
		/** @var integer|null */
		protected $hotspot__y = null;
		/** @var null|string */
		protected $photomicrograph_id = null;

		/**
		 * @param null|string $photomicrographId
		 * @param integer|null $hotspotX
		 * @param integer|null $hotspotY
		 */
		public function __construct ($photomicrographId = null, $hotspotX = null, $hotspotY = null) {
			$this->photomicrograph_id = $photomicrographId;
			$this->hotspot__x = $hotspotX;
			$this->hotspot__y = $hotspotY;
		}

		/**
		 * @return integer|null
		 */
		public function getHotspotX () {
			return $this->hotspot__x;
		}

		/**
		 * @return integer|null
		 */
		public function getHotspotY () {
			return $this->hotspot__y;
		}

		/**
		 * @return null|string
		 */
		public function getPhotomicrographId () {
			return $this->photomicrograph_id;
		}
	}
