<?php
	namespace sednasoft\virmisco\readlayer\valueobject;
	/**
	 * Do not edit. This class was automatically generated by codegen/read-layer/generator.php on
	 * 2016-01-13T22:53:08+01:00
	 */
	class PhotomicrographDigitizationData {
		/** @var integer|null */
		protected $color_depth = null;
		/** @var integer|null */
		protected $height = null;
		/** @var double|null */
		protected $reproduction_scale_horizontal = null;
		/** @var double|null */
		protected $reproduction_scale_vertical = null;
		/** @var integer|null */
		protected $width = null;

		/**
		 * @param integer|null $width
		 * @param integer|null $height
		 * @param integer|null $colorDepth
		 * @param double|null $reproductionScaleHorizontal
		 * @param double|null $reproductionScaleVertical
		 */
		public function __construct ($width = null, $height = null, $colorDepth = null, $reproductionScaleHorizontal = null, $reproductionScaleVertical = null) {
			$this->width = $width;
			$this->height = $height;
			$this->color_depth = $colorDepth;
			$this->reproduction_scale_horizontal = $reproductionScaleHorizontal;
			$this->reproduction_scale_vertical = $reproductionScaleVertical;
		}

		/**
		 * @return integer|null
		 */
		public function getColorDepth () {
			return $this->color_depth;
		}

		/**
		 * @return integer|null
		 */
		public function getHeight () {
			return $this->height;
		}

		/**
		 * @return double|null
		 */
		public function getReproductionScaleHorizontal () {
			return $this->reproduction_scale_horizontal;
		}

		/**
		 * @return double|null
		 */
		public function getReproductionScaleVertical () {
			return $this->reproduction_scale_vertical;
		}

		/**
		 * @return integer|null
		 */
		public function getWidth () {
			return $this->width;
		}
	}
