<?php
	namespace sednasoft\virmisco\readlayer\entity;
	/**
	 * Do not edit. This class was automatically generated by codegen/read-layer/generator.php on
	 * 2016-01-13T22:53:08+01:00
	 */
	class CarrierScan {
		/** @var null|string */
		protected $creation_time = null;
		/** @var string */
		protected $id = "";
		/** @var null|string */
		protected $modification_time = null;
		/** @var string */
		protected $real_path = "";
		/** @var string */
		protected $specimen_carrier_id = "";
		/** @var null|string */
		protected $uri = null;

		/**
		 * @return null|string
		 */
		public function getCreationTime () {
			return $this->creation_time;
		}

		/**
		 * @return string
		 */
		public function getId () {
			return $this->id;
		}

		/**
		 * @return null|string
		 */
		public function getModificationTime () {
			return $this->modification_time;
		}

		/**
		 * @return string
		 */
		public function getRealPath () {
			return $this->real_path;
		}

		/**
		 * @return string
		 */
		public function getSpecimenCarrierId () {
			return $this->specimen_carrier_id;
		}

		/**
		 * @return null|string
		 */
		public function getUri () {
			return $this->uri;
		}
	}
