<?php
	namespace sednasoft\virmisco\readlayer\entity;
	use sednasoft\virmisco\readlayer\valueobject\OrganismIdentification;
	use sednasoft\virmisco\readlayer\valueobject\OrganismTypeDesignation;
	/**
	 * Do not edit. This class was automatically generated by codegen/read-layer/generator.php on
	 * 2016-01-13T22:53:08+01:00
	 */
	class Organism {
		/** @var string */
		public static $identificationClass = "sednasoft\\virmisco\\readlayer\\valueobject\\OrganismIdentification";
		/** @var string */
		public static $typeDesignationClass = "sednasoft\\virmisco\\readlayer\\valueobject\\OrganismTypeDesignation";
		/** @var null|string */
		protected $higher_taxa = null;
		/** @var string */
		protected $id = "";
		/** @var null|string */
		protected $identification__identifier = null;
		/** @var null|string */
		protected $identification__qualifier = null;
		/** @var null|string */
		protected $phase_or_stage = null;
		/** @var null|string */
		protected $remarks = null;
		/** @var string */
		protected $sequence_number = "";
		/** @var null|string */
		protected $sex = null;
		/** @var string */
		protected $specimen_carrier_id = "";
		/** @var null|string */
		protected $type_designation__type_status = null;

		/**
		 * @return null|string
		 */
		public function getHigherTaxa () {
			return $this->higher_taxa;
		}

		/**
		 * @return string
		 */
		public function getId () {
			return $this->id;
		}

		/**
		 * @return OrganismIdentification|null
		 */
		public function getIdentification () {
			$className = self::$identificationClass;
			return $this->identification__identifier !== null || $this->identification__qualifier !== null
				? new $className($this->identification__identifier, $this->identification__qualifier)
				: null;
		}

		/**
		 * @return null|string
		 */
		public function getPhaseOrStage () {
			return $this->phase_or_stage;
		}

		/**
		 * @return null|string
		 */
		public function getRemarks () {
			return $this->remarks;
		}

		/**
		 * @return string
		 */
		public function getSequenceNumber () {
			return $this->sequence_number;
		}

		/**
		 * @return null|string
		 */
		public function getSex () {
			return $this->sex;
		}

		/**
		 * @return string
		 */
		public function getSpecimenCarrierId () {
			return $this->specimen_carrier_id;
		}

		/**
		 * @return OrganismTypeDesignation|null
		 */
		public function getTypeDesignation () {
			$className = self::$typeDesignationClass;
			return $this->type_designation__type_status !== null
				? new $className($this->type_designation__type_status)
				: null;
		}
	}
