<?php
	namespace sednasoft\virmisco\readlayer\entity;
	use sednasoft\virmisco\readlayer\valueobject\PhotomicrographCamera;
	use sednasoft\virmisco\readlayer\valueobject\PhotomicrographDetailOf;
	use sednasoft\virmisco\readlayer\valueobject\PhotomicrographDigitizationData;
	use sednasoft\virmisco\readlayer\valueobject\PhotomicrographFile;
	use sednasoft\virmisco\readlayer\valueobject\PhotomicrographMicroscope;
	use sednasoft\virmisco\readlayer\valueobject\PhotomicrographMicroscopeSettings;
	/**
	 * Do not edit. This class was automatically generated by codegen/read-layer/generator.php on
	 * 2016-01-13T22:53:08+01:00
	 */
	class Photomicrograph {
		/** @var string */
		public static $cameraClass = "sednasoft\\virmisco\\readlayer\\valueobject\\PhotomicrographCamera";
		/** @var string */
		public static $detailOfClass = "sednasoft\\virmisco\\readlayer\\valueobject\\PhotomicrographDetailOf";
		/** @var string */
		public static $digitizationDataClass = "sednasoft\\virmisco\\readlayer\\valueobject\\PhotomicrographDigitizationData";
		/** @var string */
		public static $fileClass = "sednasoft\\virmisco\\readlayer\\valueobject\\PhotomicrographFile";
		/** @var string */
		public static $microscopeClass = "sednasoft\\virmisco\\readlayer\\valueobject\\PhotomicrographMicroscope";
		/** @var string */
		public static $microscopeSettingsClass = "sednasoft\\virmisco\\readlayer\\valueobject\\PhotomicrographMicroscopeSettings";
		/** @var integer|null */
		protected $camera__active_pixels_hor = null;
		/** @var integer|null */
		protected $camera__active_pixels_ver = null;
		/** @var null|string */
		protected $camera__adc_resolution = null;
		/** @var null|string */
		protected $camera__camera_article_or_serial_number = null;
		/** @var null|string */
		protected $camera__camera_maker = null;
		/** @var null|string */
		protected $camera__camera_name = null;
		/** @var null|string */
		protected $camera__capture_format = null;
		/** @var double|null */
		protected $camera__chip_height = null;
		/** @var double|null */
		protected $camera__chip_width = null;
		/** @var null|string */
		protected $camera__color_filter_array = null;
		/** @var double|null */
		protected $camera__dynamic_range = null;
		/** @var null|string */
		protected $camera__optical_format = null;
		/** @var double|null */
		protected $camera__pixel_height = null;
		/** @var double|null */
		protected $camera__pixel_width = null;
		/** @var null|string */
		protected $camera__protective_color_filter = null;
		/** @var null|string */
		protected $camera__readout_noise = null;
		/** @var null|string */
		protected $camera__sensor_article_or_serial_number = null;
		/** @var null|string */
		protected $camera__sensor_maker = null;
		/** @var null|string */
		protected $camera__sensor_name = null;
		/** @var double|null */
		protected $camera__snr_max = null;
		/** @var null|string */
		protected $creator_capturing = null;
		/** @var null|string */
		protected $creator_processing = null;
		/** @var integer|null */
		protected $detail_of__hotspot__x = null;
		/** @var integer|null */
		protected $detail_of__hotspot__y = null;
		/** @var null|string */
		protected $detail_of__photomicrograph_id = null;
		/** @var integer|null */
		protected $digitization_data__color_depth = null;
		/** @var integer|null */
		protected $digitization_data__height = null;
		/** @var double|null */
		protected $digitization_data__reproduction_scale_horizontal = null;
		/** @var double|null */
		protected $digitization_data__reproduction_scale_vertical = null;
		/** @var integer|null */
		protected $digitization_data__width = null;
		/** @var null|string */
		protected $file__creation_time = null;
		/** @var null|string */
		protected $file__modification_time = null;
		/** @var null|string */
		protected $file__real_path = null;
		/** @var null|string */
		protected $file__uri = null;
		/** @var string */
		protected $id = "";
		/** @var null|string */
		protected $microscope__camera_mount_adapter_article_or_serial_number = null;
		/** @var double|null */
		protected $microscope__camera_mount_adapter_magnification = null;
		/** @var null|string */
		protected $microscope__camera_mount_adapter_maker = null;
		/** @var null|string */
		protected $microscope__camera_mount_adapter_name = null;
		/** @var null|string */
		protected $microscope__condenser_article_or_serial_number = null;
		/** @var null|string */
		protected $microscope__condenser_maker = null;
		/** @var null|string */
		protected $microscope__condenser_name = null;
		/** @var null|string */
		protected $microscope__condenser_turret_prism_article_or_serial_number = null;
		/** @var null|string */
		protected $microscope__condenser_turret_prism_maker = null;
		/** @var null|string */
		protected $microscope__condenser_turret_prism_name = null;
		/** @var null|string */
		protected $microscope__dic_turret_prism_article_or_serial_number = null;
		/** @var null|string */
		protected $microscope__dic_turret_prism_maker = null;
		/** @var null|string */
		protected $microscope__dic_turret_prism_name = null;
		/** @var null|string */
		protected $microscope__magnification_changer_article_or_serial_number = null;
		/** @var null|string */
		protected $microscope__magnification_changer_maker = null;
		/** @var null|string */
		protected $microscope__magnification_changer_name = null;
		/** @var null|string */
		protected $microscope__nosepiece_objective_article_or_serial_number = null;
		/** @var double|null */
		protected $microscope__nosepiece_objective_magnification = null;
		/** @var null|string */
		protected $microscope__nosepiece_objective_maker = null;
		/** @var null|string */
		protected $microscope__nosepiece_objective_name = null;
		/** @var double|null */
		protected $microscope__nosepiece_objective_numerical_aperture = null;
		/** @var null|string */
		protected $microscope__nosepiece_objective_type = null;
		/** @var null|string */
		protected $microscope__ports_article_or_serial_number = null;
		/** @var null|string */
		protected $microscope__ports_maker = null;
		/** @var null|string */
		protected $microscope__ports_name = null;
		/** @var null|string */
		protected $microscope__stand_article_or_serial_number = null;
		/** @var null|string */
		protected $microscope__stand_maker = null;
		/** @var null|string */
		protected $microscope__stand_name = null;
		/** @var double|null */
		protected $microscope_settings__aperture_diaphragm_opening = null;
		/** @var null|string */
		protected $microscope_settings__contrast_method = null;
		/** @var double|null */
		protected $microscope_settings__dic_prism_position = null;
		/** @var double|null */
		protected $microscope_settings__field_diaphragm_opening = null;
		/** @var double|null */
		protected $microscope_settings__magnification_changer_magnification = null;
		/** @var string */
		protected $organism_id = "";
		/** @var null|string */
		protected $presentation_uri = null;
		/** @var null|string */
		protected $title = null;

		/**
		 * @return PhotomicrographCamera|null
		 */
		public function getCamera () {
			$className = self::$cameraClass;
			return $this->camera__camera_maker !== null || $this->camera__camera_name !== null || $this->camera__camera_article_or_serial_number !== null || $this->camera__sensor_maker !== null || $this->camera__sensor_name !== null || $this->camera__sensor_article_or_serial_number !== null || $this->camera__optical_format !== null || $this->camera__capture_format !== null || $this->camera__chip_width !== null || $this->camera__chip_height !== null || $this->camera__pixel_width !== null || $this->camera__pixel_height !== null || $this->camera__active_pixels_hor !== null || $this->camera__active_pixels_ver !== null || $this->camera__color_filter_array !== null || $this->camera__protective_color_filter !== null || $this->camera__adc_resolution !== null || $this->camera__dynamic_range !== null || $this->camera__snr_max !== null || $this->camera__readout_noise !== null
				? new $className($this->camera__camera_maker, $this->camera__camera_name, $this->camera__camera_article_or_serial_number, $this->camera__sensor_maker, $this->camera__sensor_name, $this->camera__sensor_article_or_serial_number, $this->camera__optical_format, $this->camera__capture_format, $this->camera__chip_width, $this->camera__chip_height, $this->camera__pixel_width, $this->camera__pixel_height, $this->camera__active_pixels_hor, $this->camera__active_pixels_ver, $this->camera__color_filter_array, $this->camera__protective_color_filter, $this->camera__adc_resolution, $this->camera__dynamic_range, $this->camera__snr_max, $this->camera__readout_noise)
				: null;
		}

		/**
		 * @return null|string
		 */
		public function getCreatorCapturing () {
			return $this->creator_capturing;
		}

		/**
		 * @return null|string
		 */
		public function getCreatorProcessing () {
			return $this->creator_processing;
		}

		/**
		 * @return PhotomicrographDetailOf|null
		 */
		public function getDetailOf () {
			$className = self::$detailOfClass;
			return $this->detail_of__photomicrograph_id !== null || $this->detail_of__hotspot__x !== null || $this->detail_of__hotspot__y !== null
				? new $className($this->detail_of__photomicrograph_id, $this->detail_of__hotspot__x, $this->detail_of__hotspot__y)
				: null;
		}

		/**
		 * @return PhotomicrographDigitizationData|null
		 */
		public function getDigitizationData () {
			$className = self::$digitizationDataClass;
			return $this->digitization_data__width !== null || $this->digitization_data__height !== null || $this->digitization_data__color_depth !== null || $this->digitization_data__reproduction_scale_horizontal !== null || $this->digitization_data__reproduction_scale_vertical !== null
				? new $className($this->digitization_data__width, $this->digitization_data__height, $this->digitization_data__color_depth, $this->digitization_data__reproduction_scale_horizontal, $this->digitization_data__reproduction_scale_vertical)
				: null;
		}

		/**
		 * @return PhotomicrographFile|null
		 */
		public function getFile () {
			$className = self::$fileClass;
			return $this->file__real_path !== null || $this->file__uri !== null || $this->file__creation_time !== null || $this->file__modification_time !== null
				? new $className($this->file__real_path, $this->file__uri, $this->file__creation_time, $this->file__modification_time)
				: null;
		}

		/**
		 * @return string
		 */
		public function getId () {
			return $this->id;
		}

		/**
		 * @return PhotomicrographMicroscope|null
		 */
		public function getMicroscope () {
			$className = self::$microscopeClass;
			return $this->microscope__stand_maker !== null || $this->microscope__stand_name !== null || $this->microscope__stand_article_or_serial_number !== null || $this->microscope__condenser_maker !== null || $this->microscope__condenser_name !== null || $this->microscope__condenser_article_or_serial_number !== null || $this->microscope__condenser_turret_prism_maker !== null || $this->microscope__condenser_turret_prism_name !== null || $this->microscope__condenser_turret_prism_article_or_serial_number !== null || $this->microscope__nosepiece_objective_maker !== null || $this->microscope__nosepiece_objective_name !== null || $this->microscope__nosepiece_objective_article_or_serial_number !== null || $this->microscope__nosepiece_objective_type !== null || $this->microscope__nosepiece_objective_numerical_aperture !== null || $this->microscope__nosepiece_objective_magnification !== null || $this->microscope__dic_turret_prism_maker !== null || $this->microscope__dic_turret_prism_name !== null || $this->microscope__dic_turret_prism_article_or_serial_number !== null || $this->microscope__magnification_changer_maker !== null || $this->microscope__magnification_changer_name !== null || $this->microscope__magnification_changer_article_or_serial_number !== null || $this->microscope__ports_maker !== null || $this->microscope__ports_name !== null || $this->microscope__ports_article_or_serial_number !== null || $this->microscope__camera_mount_adapter_maker !== null || $this->microscope__camera_mount_adapter_name !== null || $this->microscope__camera_mount_adapter_magnification !== null || $this->microscope__camera_mount_adapter_article_or_serial_number !== null
				? new $className($this->microscope__stand_maker, $this->microscope__stand_name, $this->microscope__stand_article_or_serial_number, $this->microscope__condenser_maker, $this->microscope__condenser_name, $this->microscope__condenser_article_or_serial_number, $this->microscope__condenser_turret_prism_maker, $this->microscope__condenser_turret_prism_name, $this->microscope__condenser_turret_prism_article_or_serial_number, $this->microscope__nosepiece_objective_maker, $this->microscope__nosepiece_objective_name, $this->microscope__nosepiece_objective_article_or_serial_number, $this->microscope__nosepiece_objective_type, $this->microscope__nosepiece_objective_numerical_aperture, $this->microscope__nosepiece_objective_magnification, $this->microscope__dic_turret_prism_maker, $this->microscope__dic_turret_prism_name, $this->microscope__dic_turret_prism_article_or_serial_number, $this->microscope__magnification_changer_maker, $this->microscope__magnification_changer_name, $this->microscope__magnification_changer_article_or_serial_number, $this->microscope__ports_maker, $this->microscope__ports_name, $this->microscope__ports_article_or_serial_number, $this->microscope__camera_mount_adapter_maker, $this->microscope__camera_mount_adapter_name, $this->microscope__camera_mount_adapter_magnification, $this->microscope__camera_mount_adapter_article_or_serial_number)
				: null;
		}

		/**
		 * @return PhotomicrographMicroscopeSettings|null
		 */
		public function getMicroscopeSettings () {
			$className = self::$microscopeSettingsClass;
			return $this->microscope_settings__contrast_method !== null || $this->microscope_settings__dic_prism_position !== null || $this->microscope_settings__aperture_diaphragm_opening !== null || $this->microscope_settings__field_diaphragm_opening !== null || $this->microscope_settings__magnification_changer_magnification !== null
				? new $className($this->microscope_settings__contrast_method, $this->microscope_settings__dic_prism_position, $this->microscope_settings__aperture_diaphragm_opening, $this->microscope_settings__field_diaphragm_opening, $this->microscope_settings__magnification_changer_magnification)
				: null;
		}

		/**
		 * @return string
		 */
		public function getOrganismId () {
			return $this->organism_id;
		}

		/**
		 * @return null|string
		 */
		public function getPresentationUri () {
			return $this->presentation_uri;
		}

		/**
		 * @return null|string
		 */
		public function getTitle () {
			return $this->title;
		}
	}
