<?php
	namespace sednasoft\virmisco\readlayer\entity;
	/**
	 * Do not edit. This class was automatically generated by codegen/read-layer/generator.php on
	 * 2016-01-13T22:53:08+01:00
	 */
	class SpecimenCarrier {
		/** @var null|string */
		protected $carrier_number = null;
		/** @var string */
		protected $gathering_id = "";
		/** @var string */
		protected $id = "";
		/** @var null|string */
		protected $label_transcript = null;
		/** @var null|string */
		protected $owner = null;
		/** @var null|string */
		protected $preparation_type = null;
		/** @var null|string */
		protected $previous_collection = null;

		/**
		 * @return null|string
		 */
		public function getCarrierNumber () {
			return $this->carrier_number;
		}

		/**
		 * @return string
		 */
		public function getGatheringId () {
			return $this->gathering_id;
		}

		/**
		 * @return string
		 */
		public function getId () {
			return $this->id;
		}

		/**
		 * @return null|string
		 */
		public function getLabelTranscript () {
			return $this->label_transcript;
		}

		/**
		 * @return null|string
		 */
		public function getOwner () {
			return $this->owner;
		}

		/**
		 * @return null|string
		 */
		public function getPreparationType () {
			return $this->preparation_type;
		}

		/**
		 * @return null|string
		 */
		public function getPreviousCollection () {
			return $this->previous_collection;
		}
	}
